import Vue from 'vue'
import { MenuItem, Icon, Pagination, Menu, Avatar, Image, Tooltip, TableColumn, Link, Table, Badge, Form, Loading, FormItem, Autocomplete, ColorPicker, Radio, Tag, RadioGroup, Button, Tabs, Upload, Dialog, Submenu, Input, Carousel, CarouselItem, Dropdown, DropdownItem, DropdownMenu } from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
Vue.use(MenuItem)
  .use(Icon)
  .use(Menu)
  .use(Avatar)
  .use(Form)
  .use(FormItem)
  .use(Button)
  .use(Input)
  .use(Carousel)
  .use(CarouselItem)
  .use(Dropdown)
  .use(DropdownItem)
  .use(DropdownMenu)
  .use(Submenu)
  .use(Upload)
  .use(Tabs)
  .use(Dialog)
  .use(Radio)
  .use(RadioGroup)
  .use(Tag)
  .use(ColorPicker)
  .use(Autocomplete)
  .use(Loading)
  .use(Link)
  .use(Badge)
  .use(Table)
  .use(TableColumn)
  .use(Image)
  .use(Tooltip)
  .use(Pagination)
